<?php

namespace Database\Seeders;

use App\Models\AllCity;
use Illuminate\Database\Seeder;

class AllCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        AllCity::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $data = [
            ['name' => 'Isa', 'state_id' => 1],
            ['name' => 'Badiyah', 'state_id' => 2],
            ['name' => 'Hidd', 'state_id' => 3],
            ['name' => 'Mahama', 'state_id' => 5],
            ['name' => 'Manama', 'state_id' => 6],
            ['name' => 'Sitrah', 'state_id' => 7],
            ['name' => 'al-Manamah', 'state_id' => 8],
            ['name' => 'al-Muharraq', 'state_id' => 9],
            ['name' => 'ar-Rifa\'a', 'state_id' => 10],
            ['name' => 'Bayan', 'state_id' => 12],
            ['name' => 'Hawalli', 'state_id' => 12],
            ['name' => 'Massilah', 'state_id' => 12],
            ['name' => 'Mushrif', 'state_id' => 12],
            ['name' => 'Salwa\'', 'state_id' => 12],
            ['name' => 'Sha\'\'ab', 'state_id' => 12],
            ['name' => 'Subbah-as-Salim', 'state_id' => 12],
            ['name' => 'al-Funaytis', 'state_id' => 12],
            ['name' => 'al-Funaytis-al-Garbiyah', 'state_id' => 12],
            ['name' => 'al-Jabiriyah', 'state_id' => 12],
            ['name' => 'al-Karim', 'state_id' => 12],
            ['name' => 'ar-Rumaythiyah', 'state_id' => 12],
            ['name' => 'as-Salimiyah', 'state_id' => 12],
            ['name' => 'Mishref', 'state_id' => 13],
            ['name' => 'Qadesiya', 'state_id' => 14],
            ['name' => 'Safat', 'state_id' => 15],
            ['name' => 'Salmiya', 'state_id' => 16],
            ['name' => 'A\'qaylah', 'state_id' => 17],
            ['name' => 'Abu Hulayfah', 'state_id' => 17],
            ['name' => 'Dahar', 'state_id' => 17],
            ['name' => 'Desert Area', 'state_id' => 17],
            ['name' => 'Hadiyah', 'state_id' => 17],
            ['name' => 'Jabbar-al-\'Ali', 'state_id' => 17],
            ['name' => 'Shu\'aybah', 'state_id' => 17],
            ['name' => 'al-Ahmadi', 'state_id' => 17],
            ['name' => 'al-Fintas', 'state_id' => 17],
            ['name' => 'al-Fuhayhil', 'state_id' => 17],
            ['name' => 'al-Mahbulah', 'state_id' => 17],
            ['name' => 'al-Manqaf', 'state_id' => 17],
            ['name' => 'al-Wafrah', 'state_id' => 17],
            ['name' => 'ar-Riqqah', 'state_id' => 17],
            ['name' => 'as-Sabahiyah', 'state_id' => 17],
            ['name' => 'az-Zawr', 'state_id' => 17],
            ['name' => 'Umayriyah', 'state_id' => 18],
            ['name' => 'Abraq Khitan', 'state_id' => 18],
            ['name' => 'Ardiyah', 'state_id' => 18],
            ['name' => 'Fardaws', 'state_id' => 18],
            ['name' => 'Jalib ash-Shuyuh', 'state_id' => 18],
            ['name' => 'Janub-as-Surrah', 'state_id' => 18],
            ['name' => 'Khitan-al-Janubiyah', 'state_id' => 18],
            ['name' => 'Qartaba', 'state_id' => 18],
            ['name' => 'Ray', 'state_id' => 18],
            ['name' => 'Riqay', 'state_id' => 18],
            ['name' => 'Sabhan', 'state_id' => 18],
            ['name' => 'Sarbah-an-Nasr', 'state_id' => 18],
            ['name' => 'Warmawk', 'state_id' => 18],
            ['name' => 'al-Andalus', 'state_id' => 18],
            ['name' => 'al-Farwaniyah', 'state_id' => 18],
            ['name' => 'ar-Rabbiyah', 'state_id' => 18],
            ['name' => 'Amgarah', 'state_id' => 19],
            ['name' => 'Desert Area', 'state_id' => 19],
            ['name' => 'Nasim', 'state_id' => 19],
            ['name' => 'Tayma\'', 'state_id' => 19],
            ['name' => 'Uyawn', 'state_id' => 19],
            ['name' => 'Waha', 'state_id' => 19],
            ['name' => 'al-Jahra', 'state_id' => 19],
            ['name' => 'al-Qusayr', 'state_id' => 19],
            ['name' => 'as-Sulaybiyah', 'state_id' => 19],
            ['name' => 'Abullah-as-Salam', 'state_id' => 20],
            ['name' => 'Ardhiyah', 'state_id' => 20],
            ['name' => 'Banayd-al-Qar', 'state_id' => 20],
            ['name' => 'Health District', 'state_id' => 20],
            ['name' => 'Kayfan', 'state_id' => 20],
            ['name' => 'Khalidiyah', 'state_id' => 20],
            ['name' => 'Mansuriyah', 'state_id' => 20],
            ['name' => 'Nuzha', 'state_id' => 20],
            ['name' => 'Qarnadah', 'state_id' => 20],
            ['name' => 'Shamiyah', 'state_id' => 20],
            ['name' => 'ad-Da\'iyah', 'state_id' => 20],
            ['name' => 'ad-Dasma', 'state_id' => 20],
            ['name' => 'ad-Dawhah', 'state_id' => 20],
            ['name' => 'al-\'Udayliyah', 'state_id' => 20],
            ['name' => 'al-Fayha', 'state_id' => 20],
            ['name' => 'al-Kuwayt', 'state_id' => 20],
            ['name' => 'al-Qadisiyah', 'state_id' => 20],
            ['name' => 'ar-Rawdah', 'state_id' => 20],
            ['name' => 'as-Sulaybihat', 'state_id' => 20],
            ['name' => 'ash-Shuwaykh Industrial', 'state_id' => 20],
            ['name' => 'ash-Shuwaykh Reservoir', 'state_id' => 20],
            ['name' => 'Salalah', 'state_id' => 22],
            ['name' => 'Azaiba', 'state_id' => 23],
            ['name' => 'Bawshar', 'state_id' => 23],
            ['name' => 'Madinat Qabus', 'state_id' => 23],
            ['name' => 'Masqat', 'state_id' => 23],
            ['name' => 'Matrah', 'state_id' => 23],
            ['name' => 'Muscat', 'state_id' => 23],
            ['name' => 'Muttrah', 'state_id' => 23],
            ['name' => 'Qurayyat', 'state_id' => 23],
            ['name' => 'Qurm', 'state_id' => 23],
            ['name' => 'Ruwi', 'state_id' => 23],
            ['name' => 'Wadi Al Kabir', 'state_id' => 23],
            ['name' => 'as-Sib', 'state_id' => 23],
            ['name' => 'Khasab', 'state_id' => 24],
            ['name' => 'Rusayl', 'state_id' => 25],
            ['name' => 'Bahla\'', 'state_id' => 27],
            ['name' => 'Nizwa', 'state_id' => 27],
            ['name' => 'Sumayl', 'state_id' => 27],
            ['name' => 'Ibri', 'state_id' => 28],
            ['name' => 'al-Buraymi', 'state_id' => 28],
            ['name' => 'Al khuwair', 'state_id' => 29],
            ['name' => 'Barkah', 'state_id' => 29],
            ['name' => 'Saham', 'state_id' => 29],
            ['name' => 'Shinas', 'state_id' => 29],
            ['name' => 'Suhar', 'state_id' => 29],
            ['name' => 'al-Khaburah', 'state_id' => 29],
            ['name' => 'al-Masna\'ah', 'state_id' => 29],
            ['name' => 'ar-Rustaq', 'state_id' => 29],
            ['name' => 'as-Suwayq', 'state_id' => 29],
            ['name' => 'Ibra', 'state_id' => 30],
            ['name' => 'Sur', 'state_id' => 30],
            ['name' => 'al-Mudaybi', 'state_id' => 30],
            ['name' => 'Doha', 'state_id' => 31],
            ['name' => 'Umm Bab', 'state_id' => 32],
            ['name' => 'ad-Dawhah', 'state_id' => 34],
            ['name' => 'al-Ghuwayriyah', 'state_id' => 35],
            ['name' => 'Dukhan', 'state_id' => 36],
            ['name' => 'al-Jumayliyah', 'state_id' => 36],
            ['name' => 'al-Khawr', 'state_id' => 37],
            ['name' => 'Musay\'id', 'state_id' => 38],
            ['name' => 'al-Wakrah', 'state_id' => 38],
            ['name' => 'al-Wukayr', 'state_id' => 38],
            ['name' => 'ar-Rayyan', 'state_id' => 39],
            ['name' => 'ash-Shahaniyah', 'state_id' => 39],
            ['name' => 'ar-Ruways', 'state_id' => 40],
            ['name' => 'Mahayel', 'state_id' => 42],
            ['name' => 'Abha', 'state_id' => 44],
            ['name' => 'Abu \'Aris', 'state_id' => 44],
            ['name' => 'Khamis Mushayt', 'state_id' => 44],
            ['name' => 'Qal\'at Bishah', 'state_id' => 44],
            ['name' => 'Ha\'il', 'state_id' => 47],
            ['name' => 'Jawf', 'state_id' => 48],
            ['name' => 'Sakakah', 'state_id' => 48],
            ['name' => 'Jizan', 'state_id' => 49],
            ['name' => 'Sabya', 'state_id' => 49],
            ['name' => 'Makkah', 'state_id' => 50],
            ['name' => 'Rabig', 'state_id' => 50],
            ['name' => 'al-Hawiyah', 'state_id' => 50],
            ['name' => 'at-Ta\'if', 'state_id' => 50],
            ['name' => 'Dar\'iyah', 'state_id' => 51],
            ['name' => 'Najran', 'state_id' => 51],
            ['name' => 'Sharurah', 'state_id' => 51],
            ['name' => 'Unayzah', 'state_id' => 52],
            ['name' => 'Buraydah', 'state_id' => 52],
            ['name' => 'ar-Rass', 'state_id' => 52],
            ['name' => 'Tabuk', 'state_id' => 53],
            ['name' => 'Umm Lajj', 'state_id' => 53],
            ['name' => 'al-Bahah', 'state_id' => 55],
            ['name' => 'Ara\'ar', 'state_id' => 56],
            ['name' => 'Rafha', 'state_id' => 56],
            ['name' => 'Turayf', 'state_id' => 56],
            ['name' => 'al-Qurayyat', 'state_id' => 56],
            ['name' => 'Yanbu', 'state_id' => 57],
            ['name' => 'al-Madinah', 'state_id' => 57],
            ['name' => 'Afif', 'state_id' => 58],
            ['name' => 'ad-Dawadimi', 'state_id' => 58],
            ['name' => 'ad-Dilam', 'state_id' => 58],
            ['name' => 'al-Kharj', 'state_id' => 58],
            ['name' => 'al-Majma\'ah', 'state_id' => 58],
            ['name' => 'ar-Riyad', 'state_id' => 58],
            ['name' => 'az-Zulfi', 'state_id' => 58],
            ['name' => 'Ajman', 'state_id' => 60],
            ['name' => 'Al Qusais', 'state_id' => 61],
            ['name' => 'Deira', 'state_id' => 61],
            ['name' => 'Dubai', 'state_id' => 61],
            ['name' => 'Jebel Ali', 'state_id' => 61],
            ['name' => 'Sharjah', 'state_id' => 63],
            ['name' => 'Khawr Fakkan', 'state_id' => 65],
            ['name' => 'al-Fujayrah', 'state_id' => 65],
        ];
        AllCity::insert($data);
    }
}
